### ISSUE TITLE
Standardize the encoding name

### ISSUE THREAD

**Issue by bamtor** [google/compact_enc_det#1]
(originally reported by jshin@chromium.org)

Encoding names are different from HTML5/WHATWG encoding specs. Blink has encoding aliases to make up for those differences, but we can standardize the encoding name in CED (at least when it's built with 'HTML5' defined, which we need to introduce to CED)

**Comment by JinsukKim** [comment]
Closing this issue. See e21eb6aed10b9f6e2727f136c52420033214d458
