### ISSUE TITLE
can't use it to build a shared library

### ISSUE THREAD

**Issue by sify21** [google/compact_enc_det#6]
I use this cmd:
```
g++ -fPIC -std=c++11 -I /path/to/compact_enc_det -I ${JAVA_HOME}/include -I ${JAVA_HOME}/include/linux -shared -o libmycode.so mycode.c -Wl,-whole-archive libced.a  -Wl,-no-whole-archive
```
and the output is:
```
/usr/bin/ld: libced.a(compact_enc_det.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
libced.a(compact_enc_det.cc.o): error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by JinsukKim** [comment]
> /usr/bin/ld: libced.a(compact_enc_det.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

As the error message says, please rebuild  `libced.a` with `-fPIC` option:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wno-narrowing -fPIC")
```

**Comment by sify21** [comment]
Thank you so much! Now i can use it in java!

**Comment by sify21** [comment]
Thanks for your help, I can use the library in java now. But there is a problem, I cant directly use the encoding_name returned by "EncodingName(Encoding)".  for example when "GB" is returned, I can't do this in java:
```
new String(byte[], "GB")
```
Is there a mapping? Or where can I find all values returned by "EncodingName(Encoding)", so I can map them myself?

**Comment by sify21** [comment]
I just found I can use most names returned by "MimeEncodingName(Encoding)", but not all of them, for example "x-binaryenc"

**Comment by JinsukKim** [comment]
There are a few encoding results whose corresponding mime charset name is not well determined . Feel free to make suggestions or modify the library to suit your needs.
